### ISSUE TITLE
Sporatic uncaught exception generating openapi spec relating to dj_rest_auth: AttributeError: 'NoneType' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by bradydean** [tfranzel/drf-spectacular#1122]
**Describe the bug**

I have a `/openapi` endpoint, and occasionally the API fails with this exception. This project does not use `dj_rest_auth` so I am not sure why there is an attempt to import it. This happens a few times a day, but most of the time the spec generates successfully.

```
Traceback (most recent call last):
  File "/home/app/.cache/pypoetry/virtualenvs/recovery-platform-BwZRr09X-py3.11/lib/python3.11/site-packages/drf_spectacular/plumbing.py", line 747, in _load_class
    cls.target_class = import_string(cls.target_class)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/app/.cache/pypoetry/virtualenvs/recovery-platform-BwZRr09X-py3.11/lib/python3.11/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/app/.cache/pypoetry/virtualenvs/recovery-platform-BwZRr09X-py3.11/lib/python3.11/site-packages/django/utils/module_loading.py", line 15, in cached_import
    module = import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'dj_rest_auth'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/app/.cache/pypoetry/virtualenvs/recovery-platform-BwZRr09X-py3.11/lib/python3.11/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/home/app/.cache/pypoetry/virtualenvs/recovery-platform-BwZRr09X-py3.11/lib/python3.11/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/app/.cache/pypoetry/virtualenvs/recovery-platform-BwZRr09X-py3.11/lib/python3.11/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/home/app/.cache/pypoetry/virtualenvs/recovery-platform-BwZRr09X-py3.11/lib/python3.11/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/app/.cache/pypoetry/virtualenvs/recovery-platform-BwZRr09X-py3.11/lib/python3.11/site-packages/asgiref/sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/app/.cache/pypoetry/virtualenvs/recovery-platform-BwZRr09X-py3.11/lib/python3.11/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/app/.cache/pypoetry/virtualenvs/recovery-platform-BwZRr09X-py3.11/lib/python3.11/site-packages/asgiref/sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/app/.cache/pypoetry/virtualenvs/recovery-platform-BwZRr09X-py3.11/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/app/.cache/pypoetry/virtualenvs/recovery-platform-BwZRr09X-py3.11/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/app/.cache/pypoetry/virtualenvs/recovery-platform-BwZRr09X-py3.11/lib/python3.11/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/app/.cache/pypoetry/virtualenvs/recovery-platform-BwZRr09X-py3.11/lib/python3.11/site-packages/django/views/decorators/cache.py", line 40, in _cache_controlled
    response = viewfunc(request, *args, **kw)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/app/.cache/pypoetry/virtualenvs/recovery-platform-BwZRr09X-py3.11/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/app/.cache/pypoetry/virtualenvs/recovery-platform-BwZRr09X-py3.11/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/app/.cache/pypoetry/virtualenvs/recovery-platform-BwZRr09X-py3.11/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/app/.cache/pypoetry/virtualenvs/recovery-platform-BwZRr09X-py3.11/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/app/.cache/pypoetry/virtualenvs/recovery-platform-BwZRr09X-py3.11/lib/python3.11/site-packages/drf_spectacular/views.py", line 83, in get
    return self._get_schema_response(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/app/.cache/pypoetry/virtualenvs/recovery-platform-BwZRr09X-py3.11/lib/python3.11/site-packages/drf_spectacular/views.py", line 91, in _get_schema_response
    data=generator.get_schema(request=request, public=self.serve_public),
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/app/.cache/pypoetry/virtualenvs/recovery-platform-BwZRr09X-py3.11/lib/python3.11/site-packages/drf_spectacular/generators.py", line 268, in get_schema
    paths=self.parse(request, public),
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/app/.cache/pypoetry/virtualenvs/recovery-platform-BwZRr09X-py3.11/lib/python3.11/site-packages/drf_spectacular/generators.py", line 239, in parse
    operation = view.schema.get_operation(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/app/.cache/pypoetry/virtualenvs/recovery-platform-BwZRr09X-py3.11/lib/python3.11/site-packages/drf_spectacular/utils.py", line 422, in get_operation
    return super().get_operation(path, path_regex, path_prefix, method, registry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/app/.cache/pypoetry/virtualenvs/recovery-platform-BwZRr09X-py3.11/lib/python3.11/site-packages/drf_spectacular/openapi.py", line 78, in get_operation
    parameters = self._get_parameters()
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/app/.cache/pypoetry/virtualenvs/recovery-platform-BwZRr09X-py3.11/lib/python3.11/site-packages/drf_spectacular/openapi.py", line 239, in _get_parameters
    override_parameters = self._process_override_parameters()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/app/.cache/pypoetry/virtualenvs/recovery-platform-BwZRr09X-py3.11/lib/python3.11/site-packages/drf_spectacular/openapi.py", line 208, in _process_override_parameters
    mapped = self._map_serializer(parameter, 'request')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/app/.cache/pypoetry/virtualenvs/recovery-platform-BwZRr09X-py3.11/lib/python3.11/site-packages/drf_spectacular/openapi.py", line 909, in _map_serializer
    serializer_extension = OpenApiSerializerExtension.get_match(serializer)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/app/.cache/pypoetry/virtualenvs/recovery-platform-BwZRr09X-py3.11/lib/python3.11/site-packages/drf_spectacular/plumbing.py", line 784, in get_match
    if extension._matches(target):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/app/.cache/pypoetry/virtualenvs/recovery-platform-BwZRr09X-py3.11/lib/python3.11/site-packages/drf_spectacular/plumbing.py", line 768, in _matches
    cls._load_class()
  File "/home/app/.cache/pypoetry/virtualenvs/recovery-platform-BwZRr09X-py3.11/lib/python3.11/site-packages/drf_spectacular/plumbing.py", line 750, in _load_class
    if any(cls.target_class.startswith(app + '.') for app in installed_apps) and not cls.optional:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/app/.cache/pypoetry/virtualenvs/recovery-platform-BwZRr09X-py3.11/lib/python3.11/site-packages/drf_spectacular/plumbing.py", line 750, in <genexpr>
    if any(cls.target_class.startswith(app + '.') for app in installed_apps) and not cls.optional:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'startswith'
```

**To Reproduce**

Cannot be reproduced locally, I just have production logs of it happening.

**Expected behavior**

API spec generates successfully every time

**Comment by tfranzel** [comment]
Hi, this looks like very strange behavior. It is okay to not have `dj_rest_auth`, as these are optional imports.

drf-spectacular is deterministic and should either always fail or never fail. 

Here, we see that `target_class` is a string. Then we try to import it, if it fails we do some string formatting on that string. The assumption i being a string is broken somehow, even though it is guaranteed 2 lines prior.

https://github.com/tfranzel/drf-spectacular/blob/f31238e176c06fde20a859d591e3c5661576d44d/drf_spectacular/plumbing.py#L789

https://github.com/tfranzel/drf-spectacular/blob/f31238e176c06fde20a859d591e3c5661576d44d/drf_spectacular/plumbing.py#L772

Are you using some asynchronous framework, event loop or other parallel execution mechanisms? This looks like a race condition to me. Same with your other issue. The component registry is one of the 2 or 3 global objects inside spectacular. Everything else should be thread-safe actually.

**Comment by bradydean** [comment]
> Are you using some asynchronous framework, event loop or other parallel execution mechanisms?

Not that I am aware of, the app is pure drf, ran with daphne, fedora 39 container, I'm seeing the same errors on python3.11 and python3.12. I found logs of these errors happening as far back as Sept 11.

I'm trying to correlate these errors with container startup/shutdown but it doesn't seem like that's an issue at the moment.

**Comment by bradydean** [comment]
FWIF the exception mentioned in this issue does not appear until Oct 2.

**Comment by tfranzel** [comment]
hm... we do run tests for py 3.12 and it is safe to run spectacular with daphne or any asgi server. I use it myself that way. The last change to these parts are over 2 years ago and there was only one minor release in september with a hand full of unrelated fixes.

On first encounter, we try to import the string and set it `None` if the lib is not there. If it is `None` we do not try again. 
So while the import of the string fails, another "thread" must already set the string to `None` and so the log message formatting fails. If you look at the code, it is basically impossible to break in a single thread environment. I have no other explanation than are race condition.

**Comment by jonasN5** [comment]
Same issue here reported in our CI when using pytest-xdis to run multiple threads. Would be good to have a way to circumvent this, that is, still have the multi-threading option without the tests ending up being flaky.

**Comment by jbbqqf** [comment]
Hi! Triaging older issues — this looks like a duplicate of #1123 (same author, same `/openapi` endpoint, same flakiness profile).

Evidence:
- The discussion you (@bradydean) continued in [#1123](https://github.com/tfranzel/drf-spectacular/issues/1123) narrows the root cause down to concurrent schema-generation under ASGI workers (daphne / uvicorn / gthread), which is also what this issue describes ("happens a few times a day").
- The `dj_rest_auth` `'NoneType' object has no attribute 'startswith'` AttributeError reported here surfaces in the same race window — once `_view` is overwritten by another thread, follow-up resolution code reads `None` instead of a string and crashes in whichever introspection path happens to run first.

If this is actually a separate failure mode (e.g. you can reproduce it deterministically without concurrent requests, or it shows up in a sync wsgi worker), point me at that and I'll dig further. Otherwise would you mind closing this in favour of #1123 so the discussion stays in one place?

---
*Disclosure: I drafted this comment with help from Claude Code while triaging stale issues; the references above were verified manually.*
