### ISSUE TITLE
django.template.base.VariableDoesNotExist: Failed lookup for key [script_url]

### ISSUE THREAD

**Issue by copyNdpaste** [tfranzel/drf-spectacular#1159]
```bash
28/Jan/2024 05:55:15,013 base.py:_resolve_lookup:922 [DEBUG] Exception while resolving variable 'script_url' in template 'drf_spectacular/swagger_ui.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 875, in _resolve_lookup
    current = current[bit]
  File "/usr/local/lib/python3.9/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'script_url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 881, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(
AttributeError: type object 'RequestContext' has no attribute 'script_url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 891, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'script_url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 898, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [script_url] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0xffff73cf5040>>, 'request': <rest_framework.request.Request: GET '/api/docs'>, 'user': <django.contrib.auth.models.AnonymousUser object at 0xffff73ce2e80>, 'perms': PermWrapper(<django.contrib.auth.models.AnonymousUser object at 0xffff73ce2e80>), 'messages': <FallbackStorage: request=<WSGIRequest: GET '/api/docs'>>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}}, {}, {'title': 'API', 'swagger_ui_css': 'https://cdn.jsdelivr.net/npm/swagger-ui-dist@latest/swagger-ui.css', 'swagger_ui_bundle': 'https://cdn.jsdelivr.net/npm/swagger-ui-dist@latest/swagger-ui-bundle.js', 'swagger_ui_standalone': 'https://cdn.jsdelivr.net/npm/swagger-ui-dist@latest/swagger-ui-standalone-preset.js', 'favicon_href': 'https://cdn.jsdelivr.net/npm/swagger-ui-dist@latest/favicon-32x32.png', 'schema_url': '/api/schema', 'settings': '{\n  "deepLinking": true\n}', 'oauth2_config': '{}', 'template_name_js': 'drf_spectacular/swagger_ui.js', 'csrf_header_name': 'X-CSRFTOKEN', 'schema_auth_names': '[]'}, {'block': <Block Node: body. Contents: [<TextNode: '\n    <div id="swagger-ui"'>, <Variable Node: swagger_ui_bundle>, <TextNode: '"></script>\n    <script s'>, <Variable Node: swagger_ui_standalone>, <TextNode: '"></script>\n    '>, <IfNode>, <TextNode: '\n    '>]>}]
```

settings.py
```python
INSTALLED_APPS = [
    "drf_spectacular",

]
REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}
```

urls.py
```python
urlpatterns = [
    path(
        "api/schema",
        SpectacularAPIView.as_view(),
        name="schema",
    ),
    path(
        "api/docs",
        SpectacularSwaggerView.as_view(url_name="schema"),
        name="swagger-ui",
    ),
]
```

why VariableDoesNotExist error is raised?

**Comment by copyNdpaste** [comment]
```
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://host.docker.internal:8000",
]

CORS_ALLOW_METHODS = [
    "GET" "POST",
]

```

`http://host.docker.internal:8000`

I used this host in docker compose to connect container to local db.

**Comment by copyNdpaste** [comment]
SERVER_ENV=local ./manage.py spectacular --file schema.yaml --validate
->
Schema generation summary:
Warnings: 1 (1 unique)
Errors:   0 (0 unique)

**Comment by tfranzel** [comment]
Hi, this is highly unusual. I'm not even sure how it is possible that line 22 produces an error. By definition the `if` is safe even if the variable is not existing, in which case `false` is assumed.

https://github.com/tfranzel/drf-spectacular/blob/a616766528b9a97516b03496354a56755762f914/drf_spectacular/templates/drf_spectacular/swagger_ui.html#L22-L27

* Are you sure nothing else is broken on your side, since this works flawlessly for a lot of people and we haven't changed anything here for quite a while. 
* Do regular requests work for you? 
* Which version of Django/DRF/spectacular are you using?

**Comment by BramEsposito** [comment]
@copyNdpaste do you have Django Debug Toolbar installed? I run into these errors when the Toolbar is visible.

**Comment by vcleal** [comment]
This is just a debug level log from the 'django' logger, it logs the exception but replaces the variable with context.template.engine.string_if_invalid, which is an empty string by default, so there are no errors in request or templates rendering.
You can check the code in the file "/usr/local/lib/python3.9/site-packages/django/template/base.py" or https://github.com/django/django/blob/fa7848146738a9fe1d415ee4808664e54739eeb7/django/template/base.py#L931for example.
``` python
...
        except Exception as e:
            template_name = getattr(context, "template_name", None) or "unknown"
            logger.debug(
                "Exception while resolving variable '%s' in template '%s'.",
                bit,
                template_name,
                exc_info=True,
            )

            if getattr(e, "silent_variable_failure", False):
                current = context.template.engine.string_if_invalid
            else:
                raise

        return current
```
https://docs.djangoproject.com/en/5.0/ref/templates/api/#how-invalid-variables-are-handled

**Comment by tfranzel** [comment]
thx @vcleal this finally makes sense, I believe. Since there is no nice&short way of checking for existence, it is easier to just set this var to `None` in the main use-case.

I think this should fix it then. Feedback welcome.

**Comment by DvaMishkiLapa** [comment]
I am encountering a similar kind of error when opening the Swagger interface. Although it doesn't seem to break anything, this message is infuriating.

```py
SPECTACULAR_SETTINGS = {
    'TITLE': 'Core API',
    'DESCRIPTION': 'Core service',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': True
}
```

```
Django==5.1.2
drf-spectacular==0.27.2
```

```sh
core-1    | 2024-10-25 10:04:48 | DEBUG | django.template (base) | Exception while resolving variable 'script_url' in template 'drf_spectacular/swagger_ui.html'.
core-1    | Traceback (most recent call last):
core-1    |   File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 883, in _resolve_lookup
core-1    |     current = current[bit]
core-1    |               ~~~~~~~^^^^^
core-1    |   File "/usr/local/lib/python3.12/site-packages/django/template/context.py", line 85, in __getitem__
core-1    |     raise KeyError(key)
core-1    | KeyError: 'script_url'
core-1    | 
core-1    | During handling of the above exception, another exception occurred:
core-1    | 
core-1    | Traceback (most recent call last):
core-1    |   File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 889, in _resolve_lookup
core-1    |     if isinstance(current, BaseContext) and getattr(
core-1    |                                             ^^^^^^^^
core-1    | AttributeError: type object 'RequestContext' has no attribute 'script_url'
core-1    | 
core-1    | During handling of the above exception, another exception occurred:
core-1    | 
core-1    | Traceback (most recent call last):
core-1    |   File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 899, in _resolve_lookup
core-1    |     current = current[int(bit)]
core-1    |                       ^^^^^^^^
core-1    | ValueError: invalid literal for int() with base 10: 'script_url'
core-1    | 
core-1    | During handling of the above exception, another exception occurred:
core-1    | 
core-1    | Traceback (most recent call last):
core-1    |   File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 906, in _resolve_lookup
core-1    |     raise VariableDoesNotExist(
core-1    | django.template.base.VariableDoesNotExist: Failed lookup for key [script_url] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x7f6e3284b100>>, 'request': <rest_framework.request.Request: GET '/schema/swagger/'>, 'user': <django.contrib.auth.models.AnonymousUser object at 0x7f6e327a5fd0>, 'perms': PermWrapper(<django.contrib.auth.models.AnonymousUser object at 0x7f6e327a5fd0>), 'messages': <FallbackStorage: request=<ASGIRequest: GET '/schema/swagger/'>>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}}, {}, {'title': 'Echelon Core API', 'swagger_ui_css': 'https://cdn.jsdelivr.net/npm/swagger-ui-dist@latest/swagger-ui.css', 'swagger_ui_bundle': 'https://cdn.jsdelivr.net/npm/swagger-ui-dist@latest/swagger-ui-bundle.js', 'swagger_ui_standalone': 'https://cdn.jsdelivr.net/npm/swagger-ui-dist@latest/swagger-ui-standalone-preset.js', 'favicon_href': 'https://laolab.org/favicon.ico', 'schema_url': '/schema/', 'settings': '{\n  "deepLinking": true\n}', 'oauth2_config': '{}', 'template_name_js': 'drf_spectacular/swagger_ui.js', 'csrf_header_name': 'X-CSRFTOKEN', 'schema_auth_names': '[]'}, {'block': <Block Node: body. Contents: [<TextNode: '\n    <div id="swagger-ui"'>, <Variable Node: swagger_ui_bundle>, <TextNode: '"></script>\n    <script s'>, <Variable Node: swagger_ui_standalone>, <TextNode: '"></script>\n    '>, <IfNode>, <TextNode: '\n    '>]>}]
core-1    | 2024-10-25 10:04:48,892 DEBUG    Exception while resolving variable 'script_url' in template 'drf_spectacular/swagger_ui.html'.
core-1    | Traceback (most recent call last):
core-1    |   File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 883, in _resolve_lookup
core-1    |     current = current[bit]
core-1    |               ~~~~~~~^^^^^
core-1    |   File "/usr/local/lib/python3.12/site-packages/django/template/context.py", line 85, in __getitem__
core-1    |     raise KeyError(key)
core-1    | KeyError: 'script_url'
core-1    | 
core-1    | During handling of the above exception, another exception occurred:
core-1    | 
core-1    | Traceback (most recent call last):
core-1    |   File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 889, in _resolve_lookup
core-1    |     if isinstance(current, BaseContext) and getattr(
core-1    |                                             ^^^^^^^^
core-1    | AttributeError: type object 'RequestContext' has no attribute 'script_url'
core-1    | 
core-1    | During handling of the above exception, another exception occurred:
core-1    | 
core-1    | Traceback (most recent call last):
core-1    |   File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 899, in _resolve_lookup
core-1    |     current = current[int(bit)]
core-1    |                       ^^^^^^^^
core-1    | ValueError: invalid literal for int() with base 10: 'script_url'
core-1    | 
core-1    | During handling of the above exception, another exception occurred:
core-1    | 
core-1    | Traceback (most recent call last):
core-1    |   File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 906, in _resolve_lookup
core-1    |     raise VariableDoesNotExist(
core-1    | django.template.base.VariableDoesNotExist: Failed lookup for key [script_url] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x7f6e3284b100>>, 'request': <rest_framework.request.Request: GET '/schema/swagger/'>, 'user': <django.contrib.auth.models.AnonymousUser object at 0x7f6e327a5fd0>, 'perms': PermWrapper(<django.contrib.auth.models.AnonymousUser object at 0x7f6e327a5fd0>), 'messages': <FallbackStorage: request=<ASGIRequest: GET '/schema/swagger/'>>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}}, {}, {'title': 'Echelon Core API', 'swagger_ui_css': 'https://cdn.jsdelivr.net/npm/swagger-ui-dist@latest/swagger-ui.css', 'swagger_ui_bundle': 'https://cdn.jsdelivr.net/npm/swagger-ui-dist@latest/swagger-ui-bundle.js', 'swagger_ui_standalone': 'https://cdn.jsdelivr.net/npm/swagger-ui-dist@latest/swagger-ui-standalone-preset.js', 'favicon_href': 'https://laolab.org/favicon.ico', 'schema_url': '/schema/', 'settings': '{\n  "deepLinking": true\n}', 'oauth2_config': '{}', 'template_name_js': 'drf_spectacular/swagger_ui.js', 'csrf_header_name': 'X-CSRFTOKEN', 'schema_auth_names': '[]'}, {'block': <Block Node: body. Contents: [<TextNode: '\n    <div id="swagger-ui"'>, <Variable Node: swagger_ui_bundle>, <TextNode: '"></script>\n    <script s'>, <Variable Node: swagger_ui_standalone>, <TextNode: '"></script>\n    '>, <IfNode>, <TextNode: '\n    '>]>}]

**Comment by jbbqqf** [comment]
Hi! Triaging older issues — I think this one has shipped and can be closed.

Evidence:
- The fix was committed in [`ebe958c`](https://github.com/tfranzel/drf-spectacular/commit/ebe958c) ("mitigate false positive in Django Debug Toolbar #1159"). It defaults `script_url` to `None` in [`drf_spectacular/views.py:145`](https://github.com/tfranzel/drf-spectacular/blob/master/drf_spectacular/views.py#L145) so the template's `{% if script_url %}` no longer trips the Django Debug Toolbar variable resolver.
- Released in 0.28.0, and confirmed by @vcleal in this thread ("The newest version `0.28.0` has the fix mentioned here and avoids this log now").

If I'm wrong about something here (e.g. you see this on >= 0.28.0), point me at the version/repro and I'll dig further. Otherwise would you mind closing this out?

---
*Disclosure: I drafted this comment with help from Claude Code while triaging stale issues; the references above were verified manually.*
