### ISSUE TITLE
Version compatibility with djangorestframework-simplejwt

### ISSUE THREAD

**Issue by TusharRoy23** [tfranzel/drf-spectacular#1164]
**Describe the bug**
A bearer token has been implemented for authentication using `djangorestframework-simplejwt`. After implementing that, my API docs failed to load. Saying - `TypeError: 'str' object is not callable`.

**To Reproduce**
```
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': {
        'rest_framework_simplejwt.authentication.JWTAuthentication'  # To use Bearer token authentication
    }
}
```
If I use the default drf `TokenAuthentication` then it works.
**Packages**:
| Name        | version |
| ------------|---------|
| Django      | 4.2.7 |
| djangorestframework     | 3.14.0   |
| drf-spectacular | 0.26.5|
| djangorestframework-simplejwt | 5.3.1|

**Expected behavior**
Should see the SwaggerUI API doc.

**Comment by tfranzel** [comment]
* please provide the full stacktrace!
* `TypeError: 'str' object is not callable` does not look like it is happening on our part.
* your spectacular version is outdated.

**Comment by TusharRoy23** [comment]
```
Internal Server Error: /api/docs/
Traceback (most recent call last):
File "/py/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
 response = get_response(request)
                     ^^^^^^^^^^^^^^^^^^^^^
File "/py/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
 response = wrapped_callback(request, *callback_args, **callback_kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/py/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/py/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/py/lib/python3.11/site-packages/rest_framework/views.py", line 492, in dispatch
     request = self.initialize_request(request, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/py/lib/python3.11/site-packages/rest_framework/views.py", line 394, in initialize_request
    authenticators=self.get_authenticators(),
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
File "/py/lib/python3.11/site-packages/rest_framework/views.py", line 272, in get_authenticators
     return [auth() for auth in self.authentication_classes]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/py/lib/python3.11/site-packages/rest_framework/views.py", line 272, in <listcomp>
     return [auth() for auth in self.authentication_classes]
             ^^^^^^
TypeError: 'str' object is not callable
```
I updated the spectacular version.
If this is not about this package, can you help me to find out why is happening?
Thanks !!!

**Comment by TusharRoy23** [comment]
Never mind. The issue was in my `settings.py` file. In the `DEFAULT_AUTHENTICATION_CLASSES`, I used a dictionary but I have to use list `[]` because there will be multiple classes.
Issue resolved.
