### ISSUE TITLE
get_schema_operation_parameters attribute not found in Docker installation 

### ISSUE THREAD

**Issue by cactail** [tfranzel/drf-spectacular#1247]
**Describe the bug**
I'm getting the following error when running drf-spectacular from the command-line in a docker container
```shell
Traceback (most recent call last):
  File "/app/manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.9/site-packages/drf_spectacular/management/commands/spectacular.py", line 72, in handle
    schema = generator.get_schema(request=None, public=True)
  File "/usr/local/lib/python3.9/site-packages/drf_spectacular/generators.py", line 285, in get_schema
    paths=self.parse(request, public),
  File "/usr/local/lib/python3.9/site-packages/drf_spectacular/generators.py", line 256, in parse
    operation = view.schema.get_operation(
  File "/usr/local/lib/python3.9/site-packages/drf_spectacular/openapi.py", line 92, in get_operation
    parameters = self._get_parameters()
  File "/usr/local/lib/python3.9/site-packages/drf_spectacular/openapi.py", line 260, in _get_parameters
    **dict_helper(self._get_filter_parameters()),
  File "/usr/local/lib/python3.9/site-packages/drf_spectacular/openapi.py", line 548, in _get_filter_parameters
    parameters += filter_backend().get_schema_operation_parameters(self.view)
AttributeError: 'ModelFilter' object has no attribute 'get_schema_operation_parameters'
```

It's using python 3.9 (poetry to install dependencies and python image tag `python:3.9-slim`) and the following versions of drf, drf-spectacular and django
```
root@442efdfe0d57:/app# pip show django
Name: Django
Version: 3.2.23
Summary: A high-level Python Web framework that encourages rapid development and clean, pragmatic design.
Home-page: https://www.djangoproject.com/
Author: Django Software Foundation
Author-email: foundation@djangoproject.com
License: BSD-3-Clause
Location: /usr/local/lib/python3.9/site-packages
Requires: asgiref, pytz, sqlparse
Required-by: django-compression-middleware, django-filter, django-jinja, django-pg-returning, django-polymorphic, django-request-vars, djangorestframework, drf-spectacular, drf-yasg

root@442efdfe0d57:/app# pip show djangorestframework
Name: djangorestframework
Version: 3.12.4
Summary: Web APIs for Django, made easy.
Home-page: https://www.django-rest-framework.org/
Author: Tom Christie
Author-email: tom@tomchristie.com
License: BSD
Location: /usr/local/lib/python3.9/site-packages
Requires: django
Required-by: drf-spectacular, drf-yasg

root@442efdfe0d57:/app# pip show drf-spectacular
Name: drf-spectacular
Version: 0.27.2
Summary: Sane and flexible OpenAPI 3 schema generation for Django REST framework
Home-page: https://github.com/tfranzel/drf-spectacular
Author: T. Franzel
Author-email: tfranzel@gmail.com
License: BSD
Location: /usr/local/lib/python3.9/site-packages
Requires: Django, djangorestframework, inflection, jsonschema, PyYAML, typing-extensions, uritemplate
Required-by:
```

I added `drf-spectacular` to the `INSTALLED_APPS` setting and `'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',` to the REST_FRAMEWORK settings.

**To Reproduce**
Within the container run the following command
```shell
python manage.py spectacular --color --file schema.yml
```

**Expected behavior**
I think the expected behavior here is to return the OpenAPI schema from the project. 

Any ideas of what's wrong with my configuration?

**Comment by tfranzel** [comment]
Hi, your config is okay, your code is broken 😄 

In particular your FilterBackend `ModelFilter` class seems to be broken. DRF interface requires `get_schema_operation_parameters` to be present:

https://github.com/encode/django-rest-framework/blob/36d5c0e74f562cbe3055f0d20818bd48d3c32359/rest_framework/filters.py#L58

If this is your filter class, you just need to implement that method or just return `[]` for now.
If this is some lib, you need to implement an extension:  

https://drf-spectacular.readthedocs.io/en/latest/customization.html#declare-custom-library-filters-with-openapifilterextension

**Comment by cactail** [comment]
Thanks for such rapid response! I think we can close the Issue then, right?
