### ISSUE TITLE
get_operation() missing 2 required positional arguments: 'method' and 'registry'

### ISSUE THREAD

**Issue by codeSamuraii** [tfranzel/drf-spectacular#188]
**Describe the bug**
A traceback appears instead of the schema.

**To Reproduce**
1. Create a new virtualenv and install:
```
Django==3.1.3
djangorestframework==3.12.1
drf-spectacular==0.10.0
```
2. Create a new project with a new app.
3. Add in `settings.py`:
```python
INSTALLED_APPS = [
    # ...Django stuff...
    'rest_framework',
    'testapp',
    'drf_spectacular'
]

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}
```
4. Add in `urls.py`:
```python
from testapp.views import CandidateView
from rest_framework.schemas import get_schema_view

urlpatterns = [
    path('candidates/', CandidateView.as_view({'get': 'list'}), name='list-candidates'),
    path('schema/', get_schema_view(title='Bug reproduction', description='...'), name='schema'),
]
```
5. Add models, serializer and view :
> `models.py`
```python
from django.db import models

class Candidate(models.Model):
    id = models.IntegerField(primary_key=True)
    experience = models.IntegerField(blank=True)
```
> serializers.py
```python
from rest_framework import serializers
from testapp.models import Candidate

class CandidateSerializer(serializers.ModelSerializer):
    class Meta:
        model = Candidate
        fields = '__all__'
```

> `views.py`
```python
from rest_framework import viewsets
from testapp.models import Candidate
from testapp.serializers import CandidateSerializer


class CandidateView(viewsets.ModelViewSet):
    queryset = Candidate.objects.all()
    serializer_class = CandidateSerializer
```

6. Create migrations and apply.
7. Run `python manage.py spectacular --file schema.yml` (is it necessary ?)
8. Run server and go to `http://127.0.0.1:8000/schema`.
9. Traceback :
```
Traceback (most recent call last):
  File "/private/tmp/bug_reproduction/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/private/tmp/bug_reproduction/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/private/tmp/bug_reproduction/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/private/tmp/bug_reproduction/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/private/tmp/bug_reproduction/venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/private/tmp/bug_reproduction/venv/lib/python3.9/site-packages/rest_framework/schemas/views.py", line 48, in handle_exception
    return super().handle_exception(exc)
  File "/private/tmp/bug_reproduction/venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/private/tmp/bug_reproduction/venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/private/tmp/bug_reproduction/venv/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/private/tmp/bug_reproduction/venv/lib/python3.9/site-packages/rest_framework/schemas/views.py", line 37, in get
    schema = self.schema_generator.get_schema(request, self.public)
  File "/private/tmp/bug_reproduction/venv/lib/python3.9/site-packages/rest_framework/schemas/openapi.py", line 81, in get_schema
    operation = view.schema.get_operation(path, method)
TypeError: get_operation() missing 2 required positional arguments: 'method' and 'registry'
```

I encoutered this problem with my project so I tried again using a new and very simple app but still get the same error.
The schema generation with the `spectacular` command works fine but the view doesn't work. Using the provided `SpectacularSwaggerView` also leads to the same error.
It may be configuration-related, did I miss something in my reproduction ?

As a side-note, thank you for providing great software to the open-source community.

**Comment by tfranzel** [comment]
hi @codeSamuraii, you are using the wrong schema view. `get_schema_view` belongs to DRF not spectacular:

 ```path('schema/', get_schema_view(title='Bug reproduction', description='...'), name='schema'),```

please use 

```python
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView
urlpatterns = [
    # YOUR PATTERNS
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    # Optional UI:
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
]
```
as outlined in the readme.


> Run python manage.py spectacular --file schema.yml (is it necessary ?)

no it is not necessary, just an alternate way to generate the schema via CLI. the output is identical ( with the default visibility and permission settings)

**Comment by codeSamuraii** [comment]
Hello,

Thanks for your answer.
My mistake was that I didn't use `SpectacularSwaggerView` with `SpectacularAPIView` which it must rely on.

Have a nice day.
