### ISSUE TITLE
Out-the-box CLI Error

### ISSUE THREAD

**Issue by ZeroSum24** [tfranzel/drf-spectacular#269]
**Describe the bug**

Hi there, I'm having issues running the schema generator from the CLI and I was hoping for your help please? :)

It's flagging issues within django itself which I found odd. Here's the traceback:
```
Warning #0: could not resolve authenticator <class 'rest_framework.authentication.RemoteUserAuthentication'>. There was no OpenApiAuthenticationExtension registered for that class. Try creating one by subclassing it. Ignoring for now.
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/Users/temp/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/Users/temp/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/temp/env/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/temp/env/lib/python3.8/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/Users/temp/env/lib/python3.8/site-packages/drf_spectacular/management/commands/spectacular.py", line 50, in handle
    schema = generator.get_schema(request=None, public=True)
  File "/Users/temp/env/lib/python3.8/site-packages/drf_spectacular/generators.py", line 219, in get_schema
    paths=self.parse(request, public),
  File "/Users/temp/env/lib/python3.8/site-packages/drf_spectacular/generators.py", line 196, in parse
    operation = view.schema.get_operation(path, path_regex, method, self.registry)
  File "/Users/temp/env/lib/python3.8/site-packages/drf_spectacular/openapi.py", line 82, in get_operation
    operation['responses'] = self._get_response_bodies()
  File "/Users/temp/env/lib/python3.8/site-packages/drf_spectacular/openapi.py", line 923, in _get_response_bodies
    return {'200': self._get_response_for_code(response_serializers, '200')}
  File "/Users/temp/env/lib/python3.8/site-packages/drf_spectacular/openapi.py", line 959, in _get_response_for_code
    component = self.resolve_serializer(serializer, 'response')
  File "/Users/temp/env/lib/python3.8/site-packages/drf_spectacular/openapi.py", line 1056, in resolve_serializer
    component.schema = self._map_serializer(serializer, direction)
  File "/Users/temp/env/lib/python3.8/site-packages/drf_spectacular/openapi.py", line 641, in _map_serializer
    schema = self._map_basic_serializer(serializer, direction)
  File "/Users/temp/env/lib/python3.8/site-packages/drf_spectacular/openapi.py", line 708, in _map_basic_serializer
    schema = self._map_serializer_field(field, direction)
  File "/Users/temp/env/lib/python3.8/site-packages/drf_spectacular/openapi.py", line 423, in _map_serializer_field
    meta = self._get_serializer_field_meta(field)
  File "/Users/temp/env/lib/python3.8/site-packages/drf_spectacular/openapi.py", line 689, in _get_serializer_field_meta
    default = field.to_representation(field.default)
  File "/Users/temp/env/lib/python3.8/site-packages/rest_framework/fields.py", line 1391, in to_representation
    return duration_string(value)
  File "/Users/temp/env/lib/python3.8/site-packages/django/utils/duration.py", line 20, in duration_string
    days, hours, minutes, seconds, microseconds = _get_duration_components(duration)
  File "/Users/temp/env/lib/python3.8/site-packages/django/utils/duration.py", line 5, in _get_duration_components
    days = duration.days
AttributeError: 'int' object has no attribute 'days'
```

**To Reproduce**
It would be most helpful to provide a small snippet to see how the bug was provoked.

I followed the initial two steps for integrating drf-spectacular into the settings.py and then ran:
` python3 manage.py spectacular --file schema.yml`

The requirements.txt for my app:

```
asgiref==3.2.10
django==3.0.*
django-cockroachdb==3.0.*
djangorestframework==3.10.*
djangorestframework-simplejwt==4.4.*
drf-spectacular==0.13.1
psycopg2>=2.8,<2.9
pytz==2020.1
sqlparse==0.3.1
```

**Expected behavior**

The schema to generate a file with some information logged to terminal as it produced the file (whatever the expected output of the CLI is, I've not seen it working just yet :) ) Thanks for your help!

**Comment by tfranzel** [comment]
hi @ZeroSum24 , this actually looks like a DRF/django usage issue. your field is a `DurationField`and the default value it has is of type `int` which does not agree with the fields serialization code.  apparently this field would like to have a `timedelta` object as default and not an `int`.

one could argue whether or not this should throw an error but at the end of the day this would most likely also fail while in usage. pretty sure this will dissappear once the field default is of the proper type.

**Comment by ZeroSum24** [comment]
Hi @tfranzel, as you said this was exactly the issue, and after identifying and fixing an erroneous serialiser I'm delighted to have got this up and running. Thanks very much for your help and your efforts for the community!
