### ISSUE TITLE
Incompatible AutoSchema used on View.

### ISSUE THREAD

**Issue by AlekseiKhatkevich** [tfranzel/drf-spectacular#276]
After instalation of the app, i got a following exception:

```
AssertionError at /api/schema/
Incompatible AutoSchema used on View. Is DRF's DEFAULT_SCHEMA_CLASS pointing to "drf_spectacular.openapi.AutoSchema" or any other drf-spectacular compatible AutoSchema?

```

I use 
```
drf-spectacular = 0.13.1
Django = 2.2.17
DRF = 3.12.2
Python= 3.9.1
```
"drf_spectacular.openapi.AutoSchema"  is specified in DRF settings:

```
api_settings.DEFAULT_SCHEMA_CLASS 
<class 'drf_spectacular.openapi.AutoSchema'>
```

same from response traceback:

`REST_FRAMEWORK = {'DEFAULT_AUTHENTICATION_CLASSES': (), 'DEFAULT_FILTER_BACKENDS': ('django_filters.rest_framework.DjangoFilterBackend',), 'DEFAULT_RENDERER_CLASSES': ['rest_framework.renderers.JSONRenderer'], 'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema'}
 `

full traceback:

```
2021-01-28 19:52:20,975 ERROR log: Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "/app/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/app/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/venv/lib/python3.9/site-packages/sentry_sdk/integrations/django/views.py", line 67, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/app/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/app/venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/app/venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/app/venv/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/venv/lib/python3.9/site-packages/drf_spectacular/views.py", line 61, in get
    return self._get_schema_response(request)
  File "/app/venv/lib/python3.9/site-packages/drf_spectacular/views.py", line 65, in _get_schema_response
    return Response(generator.get_schema(request=request, public=self.serve_public))
  File "/app/venv/lib/python3.9/site-packages/drf_spectacular/generators.py", line 219, in get_schema
    paths=self.parse(request, public),
  File "/app/venv/lib/python3.9/site-packages/drf_spectacular/generators.py", line 191, in parse
    assert isinstance(view.schema, AutoSchema), (
AssertionError: Incompatible AutoSchema used on View. Is DRF's DEFAULT_SCHEMA_CLASS pointing to "drf_spectacular.openapi.AutoSchema" or any other drf-spectacular compatible AutoSchema?
```

**Comment by tfranzel** [comment]
Hi @AlekseiKhatkevich, there must be something different in your setup as this works flawlessly for dozens of people. the versions look fine to me. settings also look good. 

the last time this came up, it was a settings confusion. are you maybe running a different `settings.py` on your instance (missing these settings)? can you inspect what `view.schema` actually contains there? i should have added this to the error message.

**Comment by AlekseiKhatkevich** [comment]
@tfranzel Thanks for the answer. I just found the origin of this. One of the DRF views had a `.schema` attribute set to an instance of  built-in DRF `AutoSchema`.
It's just a message that i have gotten from the error response was misleading me.

**Comment by tfranzel** [comment]
well it was in fact ``AssertionError: Incompatible AutoSchema used on View.`` which is quite on the point :smile: the remaining text is just the most common reason why. but i get it that this may be confusing.

added the view to easier find the source of the problem (e065499). i'll close this for now.
