### ISSUE TITLE
Translated URLs

### ISSUE THREAD

**Issue by jasilvas** [tfranzel/drf-spectacular#294]
**Describe the bug**
Generating the schema fails because we have translated URLs in our application.
```
Traceback (most recent call last):
  File "/home/jari/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/jari/venv/lib/python3.8/site-packages/drf_spectacular/views.py", line 61, in get
    return self._get_schema_response(request)
  File "/home/jari/venv/lib/python3.8/site-packages/drf_spectacular/views.py", line 65, in _get_schema_response
    return Response(generator.get_schema(request=request, public=self.serve_public))
  File "/home/jari/venv/lib/python3.8/site-packages/drf_spectacular/generators.py", line 219, in get_schema
    paths=self.parse(request, public),
  File "/home/jari/venv/lib/python3.8/site-packages/drf_spectacular/generators.py", line 187, in parse
    path = modify_for_versioning(self.inspector.patterns, method, path, view, version)
  File "/home/jari/venv/lib/python3.8/site-packages/drf_spectacular/plumbing.py", line 656, in modify_for_versioning
    urlconf=tuple(detype_pattern(p) for p in patterns)
  File "/home/jari/venv/lib/python3.8/site-packages/drf_spectacular/plumbing.py", line 656, in <genexpr>
    urlconf=tuple(detype_pattern(p) for p in patterns)
  File "/home/jari/venv/lib/python3.8/site-packages/drf_spectacular/plumbing.py", line 685, in detype_pattern
    urlconf_name=[detype_pattern(p) for p in pattern.url_patterns],
  File "/home/jari/venv/lib/python3.8/site-packages/drf_spectacular/plumbing.py", line 685, in <listcomp>
    urlconf_name=[detype_pattern(p) for p in pattern.url_patterns],
  File "/home/jari/venv/lib/python3.8/site-packages/drf_spectacular/plumbing.py", line 692, in detype_pattern
    pattern=detype_pattern(pattern.pattern),
  File "/home/jari/venv/lib/python3.8/site-packages/drf_spectacular/plumbing.py", line 705, in detype_pattern
    regex=re.sub(r'\(\?P<(\w+)>.+?\)', r'(?P<\1>[^/]+)', pattern._regex),
  File "/usr/lib/python3.8/re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
```
The regex of the pattern is `gettext_lazy()` object.

Our DRF endpoints don't have translated URLs, they are elsewhere in our app.
DRF endpoints are included to the main urls.py with namespace definition.

I couldn't get this to work with `'SERVE_URLCONF': 'api2.urls'` setting because then it couldn't find the endpoints with namespace versioning and didn't list anything in the schema.

I also tried including only DRF endpoints by filtering them in preprocessing hook but the same error happens because `detype_pattern` still goes through all the endpoints.

**Comment by tfranzel** [comment]
hi @jasilvas, you made several statement that sound weird to me.

> Our DRF endpoints don't have translated URLs, they are elsewhere in our app. DRF endpoints are included to the main urls.py with namespace definition

that can't be accurate. ``(cls is not None) and issubclass(cls, APIView)`` is  checked for every endpoint. There will be no Django endpoints in the processing, only DRF. if that would were true, you wouldn't have this problem.

> I couldn't get this to work with 'SERVE_URLCONF': 'api2.urls' setting because then it couldn't find the endpoints with namespace versioning and didn't list anything in the schema.

sounds weird as these two have very little to do with each other. setting urlconf should not impact namespace versioning afaik.

> I also tried including only DRF endpoints by filtering them in preprocessing hook but the same error happens because detype_pattern still goes through all the endpoints.

i'm pretty sure that `PREPROCESSING_HOOK` excluded endpoints will **not** show up later in `detype_pattern`. you can basically filter out the endpoint list and they don't get processed further.


apart from that happy to look at potential bugs, but we need a concrete valid AND breaking example.

**Comment by tfranzel** [comment]
closing this issue for now. feel free to comment if anything is missing or not working and we will follow-up.
