### ISSUE TITLE
Django-Trench not supported

### ISSUE THREAD

**Issue by spiria-sayeghr** [tfranzel/drf-spectacular#454]
**Describe the bug**
Using drf-spectacular and Django-Trench causes the swagger docs to no longer be generated. 

I get the following error
`django.core.exceptions.ImproperlyConfigured: "^(?P<method>[^/]+))/activate/$" is not a valid regular expression: unbalanced parenthesis at position 18`

**To Reproduce**
pip install django-trench
include `path('auth/', include('trench.urls')),` in your urls.py

**Expected behavior**

This probably has to be fixed in django-trench, but I'm not sure where to look. Is there a way in drf-spectacular to say ignore those urls?

**Comment by tfranzel** [comment]
hi! loooks like `))` is the culprit. its lacks one opening parenthesis.

i can only think of filtering out those endpoints with a `PREPROCESSING_HOOK`. please consult the docs for details on how to write one.

**Comment by spiria-sayeghr** [comment]
Yes I saw that in the error, but in the actual django-trench code it doesnt appear to have the double ))

(see https://github.com/merixstudio/django-trench/blob/master/trench/urls/base.py)

I'll look into filtering out the endpoints as a stop gap measure in preprocessing_hook. If you have any insight as to what might be going on in the file linked above, I could try to make a PR on their end to fix it.

**Comment by tfranzel** [comment]
can you provide a stacktrace for that `django.core.exceptions.ImproperlyConfigured:`? maybe we can do something about it on our end.

**Comment by spiria-sayeghr** [comment]
```
app_1    | Internal Server Error: /api/schema/
app_1    | Traceback (most recent call last):
app_1    |   File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 190, in _compile
app_1    |     return re.compile(regex)
app_1    |   File "/usr/local/lib/python3.8/re.py", line 252, in compile
app_1    |     return _compile(pattern, flags)
app_1    |   File "/usr/local/lib/python3.8/re.py", line 304, in _compile
app_1    |     p = sre_compile.compile(pattern, flags)
app_1    |   File "/usr/local/lib/python3.8/sre_compile.py", line 764, in compile
app_1    |     p = sre_parse.parse(p, flags)
app_1    |   File "/usr/local/lib/python3.8/sre_parse.py", line 962, in parse
app_1    |     raise source.error("unbalanced parenthesis")
app_1    | re.error: unbalanced parenthesis at position 18
app_1    |
app_1    | The above exception was the direct cause of the following exception:
app_1    |
app_1    | Traceback (most recent call last):
app_1    |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
app_1    |     response = get_response(request)
app_1    |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
app_1    |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
app_1    |   File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/django/views.py", line 67, in sentry_wrapped_callback
app_1    |     return callback(request, *args, **kwargs)
app_1    |   File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
app_1    |     return view_func(*args, **kwargs)
app_1    |   File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
app_1    |     return self.dispatch(request, *args, **kwargs)
app_1    |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
app_1    |     response = self.handle_exception(exc)
app_1    |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
app_1    |     self.raise_uncaught_exception(exc)
app_1    |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
app_1    |     raise exc
app_1    |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
app_1    |     response = handler(request, *args, **kwargs)
app_1    |   File "/usr/local/lib/python3.8/site-packages/drf_spectacular/views.py", line 67, in get
app_1    |     return self._get_schema_response(request)
app_1    |   File "/usr/local/lib/python3.8/site-packages/drf_spectacular/views.py", line 71, in _get_schema_response
app_1    |     return Response(generator.get_schema(request=request, public=self.serve_public))
app_1    |   File "/usr/local/lib/python3.8/site-packages/drf_spectacular/generators.py", line 230, in get_schema
app_1    |     paths=self.parse(request, public),
app_1    |   File "/usr/local/lib/python3.8/site-packages/drf_spectacular/generators.py", line 191, in parse
app_1    |     path = modify_for_versioning(self.inspector.patterns, method, path, view, version)
app_1    |   File "/usr/local/lib/python3.8/site-packages/drf_spectacular/plumbing.py", line 686, in modify_for_versioning
app_1    |     view.request.resolver_match = get_resolver(
app_1    |   File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 558, in resolve
app_1    |     sub_match = pattern.resolve(new_path)
app_1    |   File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 558, in resolve
app_1    |     sub_match = pattern.resolve(new_path)
app_1    |   File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 558, in resolve
app_1    |     sub_match = pattern.resolve(new_path)
app_1    |   File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 358, in resolve
app_1    |     match = self.pattern.match(path)
app_1    |   File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 157, in match
app_1    |     match = self.regex.search(path)
app_1    |   File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 105, in __get__
app_1    |     instance.__dict__['regex'] = instance._compile(pattern)
app_1    |   File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 192, in _compile
app_1    |     raise ImproperlyConfigured(
app_1    | django.core.exceptions.ImproperlyConfigured: "^(?P<method>[^/]+))/activate/$" is not a valid regular expression: unbalanced parenthesis at position 18
app_1    | [07/Jul/2021 13:25:08] "GET /api/schema/ HTTP/1.1" 500 177508
```

**Comment by tfranzel** [comment]
i assume you are using namespace versioning. the problem is likely located here: https://github.com/tfranzel/drf-spectacular/blob/475e4110a7f13b59429ba658eb340b95d8b46b3b/drf_spectacular/plumbing.py#L810-L816

we detype the regex in the path to allow for schema parsing. i suspect the regex for replacing the regex with an "all matching" regex fails.

so the output of that detyping is likely missing a parenthesis and that is what breaks the processing.

**Comment by tfranzel** [comment]
what puzzles me is that we introduced a state machine for processing regex exactly to prevent that issue.

https://github.com/tfranzel/drf-spectacular/blob/cd8f73c34412cf1613d7dbffed6eb6a004945af6/drf_spectacular/plumbing.py#L738

**Comment by spiria-sayeghr** [comment]
Oof, thanks for that info. I was using spectacular 0.14 and I just upgraded to 0.17.2 and the issue is resolved there.

Thanks for the state machine!
