### ISSUE TITLE
0.9.5: TypeError: map_serializer_field() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by jayvdb** [tfranzel/drf-spectacular#58]
Upgrading from 0.9.3 ..

```py
Traceback (most recent call last):
  File "./manage.py", line 46, in <module>
    main()
  File "./manage.py", line 42, in main
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python3.8/site-packages/drf_spectacular/management/commands/spectacular.py", line 44, in handle
    schema = generator.get_schema(request=None, public=True)
  File "/usr/lib/python3.8/site-packages/drf_spectacular/generators.py", line 153, in get_schema
    paths=self.parse(request, public),
  File "/usr/lib/python3.8/site-packages/drf_spectacular/generators.py", line 133, in parse
    operation = view.schema.get_operation(path, path_regex, method, self.registry)
  File "/usr/lib/python3.8/site-packages/drf_spectacular/openapi.py", line 77, in get_operation
    operation['responses'] = self._get_response_bodies()
  File "/usr/lib/python3.8/site-packages/drf_spectacular/openapi.py", line 816, in _get_response_bodies
    return {'200': self._get_response_for_code(response_serializers)}
  File "/usr/lib/python3.8/site-packages/drf_spectacular/openapi.py", line 841, in _get_response_for_code
    component = self.resolve_serializer(serializer, 'response')
  File "/usr/lib/python3.8/site-packages/drf_spectacular/openapi.py", line 913, in resolve_serializer
    component.schema = self._map_serializer(serializer, direction)
  File "/usr/lib/python3.8/site-packages/drf_spectacular/openapi.py", line 582, in _map_serializer
    schema = self._map_basic_serializer(serializer, direction)
  File "/usr/lib/python3.8/site-packages/drf_spectacular/openapi.py", line 636, in _map_basic_serializer
    schema = self._map_serializer_field(field, direction)
  File "/usr/lib/python3.8/site-packages/drf_spectacular/openapi.py", line 419, in _map_serializer_field
    schema = self.resolve_serializer(field.child, direction).ref
  File "/usr/lib/python3.8/site-packages/drf_spectacular/openapi.py", line 913, in resolve_serializer
    component.schema = self._map_serializer(serializer, direction)
  File "/usr/lib/python3.8/site-packages/drf_spectacular/openapi.py", line 582, in _map_serializer
    schema = self._map_basic_serializer(serializer, direction)
  File "/usr/lib/python3.8/site-packages/drf_spectacular/openapi.py", line 636, in _map_basic_serializer
    schema = self._map_serializer_field(field, direction)
  File "/usr/lib/python3.8/site-packages/drf_spectacular/openapi.py", line 409, in _map_serializer_field
    schema = serializer_field_extension.map_serializer_field(self, direction)
TypeError: map_serializer_field() takes 2 positional arguments but 3 were given
```

In case this is the cause, I am using the fixes from here https://gist.github.com/tfranzel/c29f6b79967c6d4b89b78e779e2a798f

**Comment by tfranzel** [comment]
the interface had to gain a `direction` parameter in 0.9.5. i updated the gist accordinly just now.

**Comment by jayvdb** [comment]
Great. Thanks for the very quick response.

**Comment by jayvdb** [comment]
(Oh, and the cleaned up 'description' text values is a wonderful sight for very sore eyes.)
