### ISSUE TITLE
Unable to generate docs - Incompatible AutoSchema error

### ISSUE THREAD

**Issue by nathanmrtns** [tfranzel/drf-spectacular#668]
This is more a question to check if its compatible to Django 3.13.1, because I'm getting an error.
I thought it was django version and downgraded to 3.13.0 but the problem remained.

After installation of the app, I got a following exception:

AssertionError at /api/schema/
Incompatible AutoSchema used on View. Is DRF's DEFAULT_SCHEMA_CLASS pointing to "drf_spectacular.openapi.AutoSchema" or any other drf-spectacular compatible AutoSchema?

I use
```
drf-spectacular = "^0.21.2"
django = "==3.2.12"
djangorestframework = "==3.13.1"
python = "^3.9"
```

"drf_spectacular.openapi.AutoSchema" is specified in DRF settings:

I checked the `api_settings.DEFAULT_SCHEMA_CLASS` and it returns `'drf_spectacular.openapi.AutoSchema'`
same from response traceback:

The error is coming from my url patterns where I use this SpectacularAPIView:
```
[...
    re_path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    # Optional UI:
    re_path(
        "docs/v4/",
        SpectacularSwaggerView.as_view(url_name="schema"),
        name="swagger-ui",
    ),
 ]
 ```
full traceback:
```
Traceback (most recent call last):
  File "/Users/nathan/workspace/mx-backend/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/nathan/workspace/mx-backend/.venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nathan/workspace/mx-backend/.venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nathan/workspace/mx-backend/.venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/nathan/workspace/mx-backend/.venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/nathan/workspace/mx-backend/.venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/nathan/workspace/mx-backend/.venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/nathan/workspace/mx-backend/.venv/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/nathan/workspace/mx-backend/.venv/lib/python3.9/site-packages/drf_spectacular/views.py", line 69, in get
    return self._get_schema_response(request)
  File "/Users/nathan/workspace/mx-backend/.venv/lib/python3.9/site-packages/drf_spectacular/views.py", line 77, in _get_schema_response
    data=generator.get_schema(request=request, public=self.serve_public),
  File "/Users/nathan/workspace/mx-backend/.venv/lib/python3.9/site-packages/drf_spectacular/generators.py", line 262, in get_schema
    paths=self.parse(request, public),
  File "/Users/nathan/workspace/mx-backend/.venv/lib/python3.9/site-packages/drf_spectacular/generators.py", line 227, in parse
    assert isinstance(view.schema, AutoSchema), (
AssertionError: Incompatible AutoSchema used on View <class 'drf_spectacular.views.SpectacularAPIView'>. Is DRF's DEFAULT_SCHEMA_CLASS pointing to "drf_spectacular.openapi.AutoSchema" or any other drf-spectacular compatible AutoSchema?
```

**Comment by tfranzel** [comment]
Hi,

it is compatible with all DRF/django combinations. are you 100% certain you have

```python
REST_FRAMEWORK = {
    # YOUR SETTINGS
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}
```

and do not overwrite this at a later stage by another additional settings file? The assert is pretty clear. It is not encountering the expected `AutoSchema` class. Maybe halt the debugger at that spot and inspect the class. pretty sure that the DRF `AutoSchema` class slips into your settings somehow.

**Comment by nathanmrtns** [comment]
My mistake, in the project I have set different REST_FRAMEWORK vars by env, I put in one and forgot the others.
Changed and it worked.
