### ISSUE TITLE
Recursion error on /api/schema/ with postprocessing hook after several calls

### ISSUE THREAD

**Issue by StopMotionCuber** [tfranzel/drf-spectacular#670]
**Describe the bug**
I'm getting a recursion error when applying `extend_decorator` multiple times in a postprocessing hook.

The important part of the recursion error:

```
Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "/home/ruben/Projects/drfSpectecularReproducer/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ruben/Projects/drfSpectecularReproducer/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ruben/Projects/drfSpectecularReproducer/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ruben/Projects/drfSpectecularReproducer/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ruben/Projects/drfSpectecularReproducer/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/ruben/Projects/drfSpectecularReproducer/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/ruben/Projects/drfSpectecularReproducer/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/ruben/Projects/drfSpectecularReproducer/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/ruben/Projects/drfSpectecularReproducer/venv/lib/python3.10/site-packages/drf_spectacular/views.py", line 69, in get
    return self._get_schema_response(request)
  File "/home/ruben/Projects/drfSpectecularReproducer/venv/lib/python3.10/site-packages/drf_spectacular/views.py", line 77, in _get_schema_response
    data=generator.get_schema(request=request, public=self.serve_public),
  File "/home/ruben/Projects/drfSpectecularReproducer/venv/lib/python3.10/site-packages/drf_spectacular/generators.py", line 262, in get_schema
    paths=self.parse(request, public),
  File "/home/ruben/Projects/drfSpectecularReproducer/venv/lib/python3.10/site-packages/drf_spectacular/generators.py", line 233, in parse
    operation = view.schema.get_operation(
  File "/home/ruben/Projects/drfSpectecularReproducer/venv/lib/python3.10/site-packages/drf_spectacular/utils.py", line 298, in get_operation
    return super().get_operation(path, path_regex, path_prefix, method, registry)
  File "/home/ruben/Projects/drfSpectecularReproducer/venv/lib/python3.10/site-packages/drf_spectacular/utils.py", line 298, in get_operation
    return super().get_operation(path, path_regex, path_prefix, method, registry)
  File "/home/ruben/Projects/drfSpectecularReproducer/venv/lib/python3.10/site-packages/drf_spectacular/utils.py", line 298, in get_operation
    return super().get_operation(path, path_regex, path_prefix, method, registry)
  [Previous line repeated 657 more times]
  File "/home/ruben/Projects/drfSpectecularReproducer/venv/lib/python3.10/site-packages/drf_spectacular/openapi.py", line 58, in get_operation
    operation = {'operationId': self.get_operation_id()}
  File "/home/ruben/Projects/drfSpectecularReproducer/venv/lib/python3.10/site-packages/drf_spectacular/utils.py", line 303, in get_operation_id
    return super().get_operation_id()
  File "/home/ruben/Projects/drfSpectecularReproducer/venv/lib/python3.10/site-packages/drf_spectacular/utils.py", line 303, in get_operation_id
    return super().get_operation_id()
  File "/home/ruben/Projects/drfSpectecularReproducer/venv/lib/python3.10/site-packages/drf_spectacular/utils.py", line 303, in get_operation_id
    return super().get_operation_id()
  [Previous line repeated 291 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**To Reproduce**
[here](https://github.com/StopMotionCuber/drfSpectacularReproducer/blob/main/drfSpectecularReproducer/schema.py#L28) I have created a small project that reproduces the error.

What the project is doing, is searching for Path parameters and annotating them correctly, based on some kwarg -> parameter mapping.
There is a loop to annotate the class 10 times in a row. This doesn't have any functional impact, but helps to trigger the bug with fewer requests.

To reproduce the error easily, you can do a `watch -n 0.1 curl http://localhost:8000/api/schema/` and see after a few seconds that a RecursionError occurs

**Expected behavior**
`http://localhost:8000/api/schema/` should not modify the internal state of the program and therefore no recursion error should occur.

**Additional Info**
I'm suspecting that annotating the class within the post processing hook again changes the state of the application and the annotation stays within the application, therefore creating a HUGE inheritance graph that is traversed here. So the inheritance for each call to `/api/schema/` is not cleaned up.
This error might be related to #597

**Comment by tfranzel** [comment]
I highly doubt this to be related to #597, but you never know.

For the concrete thing you are trying to achieve: I would subclass our `AutoSchema` (don't forget to change the `REST_FRAMEWORK` setting) and override 

https://github.com/tfranzel/drf-spectacular/blob/18b36576c7ed8c13fe472cdbaeb2b28f4b55087e/drf_spectacular/openapi.py#L142-L144 

with your (custom postprocessing) logic. Added benefit is you have access to more mechanics in this stage. Your injected parameters are used even with the added decorator as they are only appended to the list. 

fyi: Even override and removal of the injected parameters possible via decorator, in case you need it

**Comment by StopMotionCuber** [comment]
> Hi, thanks for the detailed explanation. just skimmed it but I can give you a quick heads-up. This cannot work. 

I would like to claim the opposite, as it _does_ work in just this example. Without the postprocessing hook, the parameter doesn't have a help text in Redoc. With the postprocessing hook, it has one, and also gets renamed.

> For the concrete thing you are trying to achieve: I would subclass our AutoSchema (don't forget to change the REST_FRAMEWORK setting) and override `def get_override_parameters(self)`

Thanks for the pointer. That probably makes more sense.

Feel free to close this issue, as we can probably agree that what I have done there is hacky and I wouldn't be mad if you classify the recursion error as improper use of the library.
Or re-focus this issue on documenting how to overwrite `AutoSchema`.

**Comment by tfranzel** [comment]
> I would like to claim the opposite, as it does work in just this example. Without the postprocessing hook, the parameter doesn't have a help text in Redoc. With the postprocessing hook, it has one, and also gets renamed.

it might be possible that some variable labels get reused to create that situation, though I - as the main author - don't have the slightest idea how this can reliably work. As far as I am concerned using our decorators in a postprocessing hooks is 100% undefined behavior. 

> Or re-focus this issue on documenting how to overwrite AutoSchema.

this should be pretty easy. I'll close the issue but feel free to ask a follow-up question here or in a new issue.
