### ISSUE TITLE
'ObjectIdField' object has no attribute 'is_relation' with MongoEngine

### ISSUE THREAD

**Issue by EfronC** [tfranzel/drf-spectacular#696]
I'm trying to use drf-spectacular on a project with using Mongo as DB with MongoEngine, when i installed it and tried it about a week ago, i remember it worked perfectly, but since Monday seems to have stopped working, maybe someone on my team made a change on the project that is causing it, but since the error only happens when opening the documentation, i believe there may be a problem there.

**To Reproduce**

- Create an EmbeddedDocument model with ObjectIDField
  class EmbeddedAbstractUser(EmbeddedDocument):
      id = fields.ObjectIdField()
- Add it to a data model
  class ScheduledWashService(FieldsDefaults):
       user = fields.EmbeddedDocumentField(document_type=EmbeddedAbstractUser)
- Enable the swagger view and try to open it

**Expected behavior**
The Documentation in Swagger should load without problem, but the instead launches 
![image](https://user-images.githubusercontent.com/5926318/161135676-ea078af5-3e32-452c-b270-660546081383.png)

And in the console shows:

```
Internal Server Error: /api/schema/
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
response = get_response(request)
File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
return view_func(*args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
return self.dispatch(request, *args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
response = self.handle_exception(exc)
File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
self.raise_uncaught_exception(exc)
File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
raise exc
File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
response = handler(request, *args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/drf_spectacular/views.py", line 67, in get
return self._get_schema_response(request)
File "/usr/local/lib/python3.8/site-packages/drf_spectacular/views.py", line 74, in _get_schema_response
return Response(generator.get_schema(request=request, public=self.serve_public))
File "/usr/local/lib/python3.8/site-packages/drf_spectacular/generators.py", line 259, in get_schema
paths=self.parse(request, public),
File "/usr/local/lib/python3.8/site-packages/drf_spectacular/generators.py", line 233, in parse
operation = view.schema.get_operation(
File "/usr/local/lib/python3.8/site-packages/drf_spectacular/openapi.py", line 68, in get_operation
parameters = self._get_parameters()
File "/usr/local/lib/python3.8/site-packages/drf_spectacular/openapi.py", line 210, in _get_parameters
**dict_helper(self._resolve_path_parameters(path_variables)),
File "/usr/local/lib/python3.8/site-packages/drf_spectacular/openapi.py", line 393, in _resolve_path_parameters
model_field = follow_model_field_lookup(model, model_field_name)
File "/usr/local/lib/python3.8/site-packages/drf_spectacular/plumbing.py", line 548, in follow_model_field_lookup
_, field, _, _ = query.names_to_path(lookup_splitted, query.get_meta())
File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1458, in names_to_path
if field.is_relation and not field.related_model:
AttributeError: 'ObjectIdField' object has no attribute 'is_relation'
[31/Mar/2022 19:20:37] "GET /api/schema/ HTTP/1.1" 500 146575
```

Not sure what more info i can give about this error, since i really don't know what triggered that started failing, but post this issue in case someone knows a little more.

**Comment by tfranzel** [comment]
Hi @EfronC,

* changed MongoEngine version? 
* changed Django version (3 to 4 maybe)? we use django's [names_to_path](https://github.com/tfranzel/drf-spectacular/blob/6f5bd1688182829204bb61db6a9d7903fdaf0bbe/drf_spectacular/plumbing.py#L557) which may have changed?
* changed drf-spectacular version (21.2 to 22?) imho unlikely though as nothing relevant was changed.

We do not officially support mongo engine. If a concrete issue arises I will consider fixes to make it work there too.

You would need to narrow it down with exact versions (working/not working) and a reproduction. 

>  i really don't know what triggered that started failing

yeah well.... can't help you there. You have have to analyze where/when/why it broke yourself I suppose. Then we can have a look

**Comment by EfronC** [comment]
> Hi @EfronC,
> 
> * changed MongoEngine version?
> * changed Django version (3 to 4 maybe)? we use django's [names_to_path](https://github.com/tfranzel/drf-spectacular/blob/6f5bd1688182829204bb61db6a9d7903fdaf0bbe/drf_spectacular/plumbing.py#L557) which may have changed?
> * changed drf-spectacular version (21.2 to 22?) imho unlikely though as nothing relevant was changed.
> 
> We do not officially support mongo engine. If a concrete issue arises I will consider fixes to make it work there too.
> 
> You would need to narrow it down with exact versions (working/not working) and a reproduction.
> 
> > i really don't know what triggered that started failing
> 
> yeah well.... can't help you there. You have have to analyze where/when/why it broke yourself I suppose. Then we can have a look

Hi @tfranzel ,

Sorry for the delay with an answer, i've been all afternoon with my team searching the cause. We found out that is the user model that is causing the problem, we found that, in 2 apps when it's used in the queryset, is that causes the error. We actually are getting 2 errors: 

- In the UserView we get the ObjectIdField error, we found that setting the queryset to the User Model is that causes the error.
- In other view, it launches 
```
query = model_field.model._default_manager.all().query

AttributeError: 'IntField' object has no attribute 'model'
```
Which following it seems to be related to setting filterset_fields attribute, we don't use it in any other part, so i don't know if it's affected by other kind of fields, but this at least happens when you set it to an IntField

We are still gathering more data, but for the moment this is what we got, we can make the docs work again just setting schema = None in these views, but the idea is having them show in the same.

Hope this helps to get to the problem, or at least a way to pass it, like ignoring the queryset and filter, and set the data of the docs manually.

MongoEngine: mongoengine==0.23.1
Django: Django==3.1.12
drf-spectacular: drf-spectacular==0.22.0

**Comment by EfronC** [comment]
Hi, new update about what we have been checking about this issue: 

We found what is causing it is precisely the UserModel, to be more exact, the ViewSet, here is an examplle of how we have it setted:

models.py
```
from django_mongoengine.mongo_auth.models import BaseUser
from django_mongoengine import document as django_document
from django_mongoengine import fields as django_fields

class TestUser(BaseUser, document.Document):

    email = fields.EmailField(unique=True)
    # Lots of User Fields

    meta = { 'abstract': True,'collection': f'users_testuser'
        ] }

class TestU(TestUser):
    meta = { 'allow_inheritance': True }
```

serializers.py
```
class TestUserSerializer(DocumentSerializer):

    class Meta:
        model = models.TestU
        fields = [
            'id',
            'email',
        ]
        read_only_fields = [
            'email'
        ]
```

views.py
```
class TestUserViewSet(
        ModelViewSet):
    serializer_class = serializers.TestUserSerializer
    queryset = models.TestU.objects.filter(is_active=True)
    filter_backends = [
        DjangoFilterBackend,
        filters.SearchFilter,
        filters.OrderingFilter
    ]
    #filterset_fields = ['email']
```

Just with this, the error can be replicated(In models you don't need to inherit from BaseUser for it to happen, i just added it to show we are creating a user). I believe that the problem might be the django_mongoengine library, which might not be compatible with drf-spectacular, but i'm not sure how to solve this.

I'll add this info to the first post, so it's easier to see the problem.

**Comment by jbbqqf** [comment]
Hi! Triaging older issues — I think this one is out of scope for drf-spectacular.

Evidence:
- The traceback is raised by `AttributeError: 'ObjectIdField' object has no attribute 'is_relation'`. `is_relation` is a Django ORM `Field` API ([docs](https://docs.djangoproject.com/en/stable/ref/models/fields/#django.db.models.Field.is_relation)). MongoEngine's `ObjectIdField` is a [`mongoengine.fields.ObjectIdField`](https://docs.mongoengine.org/apireference.html#mongoengine.fields.ObjectIdField) — a separate field hierarchy that doesn't ship a Django-compatible `is_relation` attribute, which is why drf-spectacular's introspection trips.
- drf-spectacular relies on Django's `names_to_path` and `Field` API in [`drf_spectacular/plumbing.py`](https://github.com/tfranzel/drf-spectacular/blob/master/drf_spectacular/plumbing.py) (see e.g. `follow_field_source` / `_get_field_from_model_or_parent`). Supporting MongoEngine's non-Django field types would need its own contrib adapter, and there isn't one — there's no `mongoengine` extension in `drf_spectacular/contrib/`.

If you think MongoEngine support is in scope (or you have a contrib module that you'd like to upstream), point me at it and I'll dig further. Otherwise — given there's been no follow-up here for 3+ years and the underlying mismatch is structural, not a bug in drf-spectacular — would you mind closing this out?

---
*Disclosure: I drafted this comment with help from Claude Code while triaging stale issues; the references above were verified manually.*
