### ISSUE TITLE
rest framework internal method get_permissions() throws an error

### ISSUE THREAD

**Issue by Fagtoy** [tfranzel/drf-spectacular#728]
When I try to see my open API schema I get an error:
```
Internal Server Error: /schema/
Traceback (most recent call last):
  File "/home/fagtoy/Desktop/work/vimpel_security_back/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/fagtoy/Desktop/work/vimpel_security_back/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/fagtoy/Desktop/work/vimpel_security_back/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/fagtoy/Desktop/work/vimpel_security_back/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/fagtoy/Desktop/work/vimpel_security_back/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/fagtoy/Desktop/work/vimpel_security_back/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/fagtoy/Desktop/work/vimpel_security_back/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/fagtoy/Desktop/work/vimpel_security_back/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/fagtoy/Desktop/work/vimpel_security_back/venv/lib/python3.10/site-packages/drf_spectacular/views.py", line 81, in get
    return self._get_schema_response(request)
  File "/home/fagtoy/Desktop/work/vimpel_security_back/venv/lib/python3.10/site-packages/drf_spectacular/views.py", line 89, in _get_schema_response
    data=generator.get_schema(request=request, public=self.serve_public),
  File "/home/fagtoy/Desktop/work/vimpel_security_back/venv/lib/python3.10/site-packages/drf_spectacular/generators.py", line 268, in get_schema
    paths=self.parse(request, public),
  File "/home/fagtoy/Desktop/work/vimpel_security_back/venv/lib/python3.10/site-packages/drf_spectacular/generators.py", line 239, in parse
    operation = view.schema.get_operation(
  File "/home/fagtoy/Desktop/work/vimpel_security_back/venv/lib/python3.10/site-packages/drf_spectacular/openapi.py", line 85, in get_operation
    auth = self.get_auth()
  File "/home/fagtoy/Desktop/work/vimpel_security_back/venv/lib/python3.10/site-packages/drf_spectacular/openapi.py", line 333, in get_auth
    perms = [p.__class__ for p in self.view.get_permissions()]
  File "/home/fagtoy/Desktop/work/vimpel_security_back/venv/lib/python3.10/site-packages/rest_framework/views.py", line 278, in get_permissions
    return [permission() for permission in self.permission_classes]
TypeError: 'OperandHolder' object is not iterable

```
it happened after I wrote my custom get_permissions(), then I completely removed it from the project, but the error didn't go away.
My workaround is to write this code:
```
if getattr(self, 'swagger_fake_view', False):
    return []
```
in get_permissions() method in APIView.

**Comment by tfranzel** [comment]
hi! that is weird. this SO question sounds awfully similar to your issue: https://stackoverflow.com/questions/53649252/django-rest-framework-basepermissionmetaclass-object-is-not-iterable

does the answer there fix your issue?

**Comment by Fagtoy** [comment]
@tfranzel hi! I have listed my permission classes correctly, so this is not the answer i am looking for :(

**Comment by tfranzel** [comment]
could you please provide the `permission_classes` of your view so I can reproduce this issue?

**Comment by Fagtoy** [comment]
I managed not to override the get_permissions() method, but to reproduce you can try:
```
permission_classes = (DjangoModelPermissions,)
```
and the get_permissions() method:
```
def get_permissions(self):
    if self.action in {'list', 'retrieve'}:
        self.permission_classes = (YourCustomPermissionClass,)
    return super().get_permissions()
```

**Comment by tfranzel** [comment]
I tried out your example with `DjangoModelPermissions` and `get_permissions` and it works just as expected. I would need a proper reproduction to proceed from here.

**Comment by Fagtoy** [comment]
I can't provide more information on this one, my get_permissions() method looked exactly like this, so I assume the issue could be closed as there are no more people who faced this error as well, thanks for trying to solve it.
