### ISSUE TITLE
DRF v 3.14.0 -- Drops `NullBooleanField`

### ISSUE THREAD

**Issue by mattstrayer** [tfranzel/drf-spectacular#817]
**Describe the bug**

DRF 3.14.0 was _just_ released, but I wanted to report this compatibility issue.

[This diff](https://github.com/encode/django-rest-framework/compare/3.13.1...3.14.0#diff-7768b980611e24de782acc70ad64cd57b9d169d42f80b200cb7c6ef277fd74dbL745-L761) shows that the `NullBooleanField` was dropped. 

Trying to generate schema using the latest `drf-spectacular` and drf 3.14.0 causes this stacktrace. 

```
127.0.0.1 - - [22/Sep/2022 13:41:07] "GET /api/schema/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/workspace/__pypackages__/3.10/lib/django/contrib/staticfiles/handlers.py", line 80, in __call__
    return self.application(environ, start_response)
  File "/workspace/__pypackages__/3.10/lib/django/core/handlers/wsgi.py", line 131, in __call__
    response = self.get_response(request)
  File "/workspace/__pypackages__/3.10/lib/django/core/handlers/base.py", line 140, in get_response
    response = self._middleware_chain(request)
  File "/workspace/__pypackages__/3.10/lib/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/workspace/__pypackages__/3.10/lib/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/workspace/__pypackages__/3.10/lib/django/core/handlers/exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/workspace/__pypackages__/3.10/lib/django_extensions/management/technical_response.py", line 40, in null_technical_500_response
    raise exc_value.with_traceback(tb)
  File "/workspace/__pypackages__/3.10/lib/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/workspace/__pypackages__/3.10/lib/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/workspace/__pypackages__/3.10/lib/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/workspace/__pypackages__/3.10/lib/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/workspace/__pypackages__/3.10/lib/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/workspace/__pypackages__/3.10/lib/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/workspace/__pypackages__/3.10/lib/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/workspace/__pypackages__/3.10/lib/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/workspace/__pypackages__/3.10/lib/drf_spectacular/views.py", line 82, in get
    return self._get_schema_response(request)
  File "/workspace/__pypackages__/3.10/lib/drf_spectacular/views.py", line 90, in _get_schema_response
    data=generator.get_schema(request=request, public=self.serve_public),
  File "/workspace/__pypackages__/3.10/lib/drf_spectacular/generators.py", line 268, in get_schema
    paths=self.parse(request, public),
  File "/workspace/__pypackages__/3.10/lib/drf_spectacular/generators.py", line 239, in parse
    operation = view.schema.get_operation(
  File "/workspace/__pypackages__/3.10/lib/drf_spectacular/openapi.py", line 82, in get_operation
    request_body = self._get_request_body()
  File "/workspace/__pypackages__/3.10/lib/drf_spectacular/openapi.py", line 1198, in _get_request_body
    schema, request_body_required = self._get_request_for_media_type(request_serializer, direction)
  File "/workspace/__pypackages__/3.10/lib/drf_spectacular/openapi.py", line 1229, in _get_request_for_media_type
    component = self.resolve_serializer(serializer, direction)
  File "/workspace/__pypackages__/3.10/lib/drf_spectacular/openapi.py", line 1496, in resolve_serializer
    component.schema = self._map_serializer(serializer, direction, bypass_extensions)
  File "/workspace/__pypackages__/3.10/lib/drf_spectacular/openapi.py", line 880, in _map_serializer
    schema = serializer_extension.map_serializer(self, direction)
  File "/workspace/__pypackages__/3.10/lib/drf_spectacular/contrib/rest_framework_simplejwt.py", line 19, in map_serializer
    return auto_schema._map_serializer(Fixed, direction)
  File "/workspace/__pypackages__/3.10/lib/drf_spectacular/openapi.py", line 882, in _map_serializer
    schema = self._map_basic_serializer(serializer, direction)
  File "/workspace/__pypackages__/3.10/lib/drf_spectacular/openapi.py", line 969, in _map_basic_serializer
    schema = self._map_serializer_field(field, direction)
  File "/workspace/__pypackages__/3.10/lib/drf_spectacular/openapi.py", line 814, in _map_serializer_field
    if isinstance(field, (serializers.BooleanField, serializers.NullBooleanField)):
AttributeError: module 'rest_framework.serializers' has no attribute 'NullBooleanField'
```
**To Reproduce**
- install django 3.14
- install latest drf-spectacular
- generate schema file 
- observe stacktrace

**Expected behavior**

Expected to not throw an error for a field that no longer exists.

**Comment by mattstrayer** [comment]
Will close mine. Thanks!

**Comment by tfranzel** [comment]
`0.24.1` just got released. cheers!
