### ISSUE TITLE
Support custom SessionAuthentication class

### ISSUE THREAD

**Issue by MissiaL** [tfranzel/drf-spectacular#9]
I have a class
```python
class SessionAuthenticationWithHeader(SessionAuthentication):
    """
    This class defines authenticate_header
    which means django'll send 401 instead of 403
    """

    def authenticate_header(self, request):
        # that's non standard auth type so browser won't show default pop-up
        # see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/WWW-Authenticate
        return 'session realm="api"'
```

When I add this class in settings
```python
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'SessionAuthenticationWithHeader',
    ),

}
```

I get an error
```
Traceback (most recent call last):
  File "./manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/opt/drf_spectacular/management/commands/spectacular.py", line 33, in handle
    schema = generator.get_schema(request=None, public=True)
  File "/opt/drf_spectacular/openapi.py", line 116, in get_schema
    'paths': self.parse(None if public else request),
  File "/opt/drf_spectacular/openapi.py", line 84, in parse
    operation = schema.get_operation(path, method, self.registry)
  File "/opt/drf_spectacular/utils.py", line 103, in get_operation
    return super().get_operation(path, method, registry)
  File "/opt/drf_spectacular/openapi.py", line 158, in get_operation
    auth = self.get_auth(path, method)
  File "/opt/drf_spectacular/utils.py", line 121, in get_auth
    return super().get_auth(path, method)
  File "/opt/drf_spectacular/openapi.py", line 184, in get_auth
    self.resolve_authentication(method, a) for a in self.view.get_authenticators()
  File "/opt/drf_spectacular/openapi.py", line 184, in <listcomp>
    self.resolve_authentication(method, a) for a in self.view.get_authenticators()
  File "/opt/drf_spectacular/openapi.py", line 789, in resolve_authentication
    raise ValueError('no auth scheme registered for {}'.format(authentication.__name__))
AttributeError: 'SessionAuthenticationWithHeader' object has no attribute '__name__'
```

**Comment by tfranzel** [comment]
you need to define a OpenAPI translation object. Override https://github.com/tfranzel/drf-spectacular/blob/master/drf_spectacular/auth.py#L10 for your needs and register ``SessionAuthenticationWithHeader`` in that class

then define ``SCHEMA_AUTHENTICATION_CLASSES`` in settings with that one added to the list ( or only what you actually need)

i'm not too happy with that solution. the mechanism might change but that will help you for now.

**Comment by MissiaL** [comment]
Okay. Thanks
