### ISSUE TITLE
NameError: name 'obj' is not defined

### ISSUE THREAD

**Issue by huynd26** [tfranzel/drf-spectacular#975]
I tried to upgrade new version but it seems it did not resolve this error.
```terminal
[2023-04-17 02:45:51,985] ERROR Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "/home/kev/.pyenv/versions/my-project/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/kev/.pyenv/versions/my-project/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kev/.pyenv/versions/my-project/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/kev/.pyenv/versions/my-project/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/kev/.pyenv/versions/my-project/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/kev/.pyenv/versions/my-project/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/kev/.pyenv/versions/my-project/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/kev/.pyenv/versions/my-project/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/kev/.pyenv/versions/my-project/lib/python3.9/site-packages/drf_spectacular/views.py", line 83, in get
    return self._get_schema_response(request)
  File "/home/kev/.pyenv/versions/my-project/lib/python3.9/site-packages/drf_spectacular/views.py", line 91, in _get_schema_response
    data=generator.get_schema(request=request, public=self.serve_public),
  File "/home/kev/.pyenv/versions/my-project/lib/python3.9/site-packages/drf_spectacular/generators.py", line 268, in get_schema
    paths=self.parse(request, public),
  File "/home/kev/.pyenv/versions/my-project/lib/python3.9/site-packages/drf_spectacular/generators.py", line 239, in parse
    operation = view.schema.get_operation(
  File "/home/kev/.pyenv/versions/my-project/lib/python3.9/site-packages/drf_spectacular/openapi.py", line 95, in get_operation
    operation['responses'] = self._get_response_bodies()
  File "/home/kev/.pyenv/versions/my-project/lib/python3.9/site-packages/drf_spectacular/openapi.py", line 1348, in _get_response_bodies
    return {'200': self._get_response_for_code(response_serializers, '200', direction=direction)}
  File "/home/kev/.pyenv/versions/my-project/lib/python3.9/site-packages/drf_spectacular/openapi.py", line 1404, in _get_response_for_code
    component = self.resolve_serializer(serializer, direction)
  File "/home/kev/.pyenv/versions/my-project/lib/python3.9/site-packages/drf_spectacular/openapi.py", line 1575, in resolve_serializer
    component.schema = self._map_serializer(serializer, direction, bypass_extensions)
  File "/home/kev/.pyenv/versions/my-project/lib/python3.9/site-packages/drf_spectacular/openapi.py", line 907, in _map_serializer
    schema = self._map_basic_serializer(serializer, direction)
  File "/home/kev/.pyenv/versions/my-project/lib/python3.9/site-packages/drf_spectacular/openapi.py", line 1005, in _map_basic_serializer
    schema = self._map_serializer_field(field, direction)
  File "/home/kev/.pyenv/versions/my-project/lib/python3.9/site-packages/drf_spectacular/openapi.py", line 874, in _map_serializer_field
    schema = self._map_response_type_hint(target)
  File "/home/kev/.pyenv/versions/my-project/lib/python3.9/site-packages/drf_spectacular/openapi.py", line 1095, in _map_response_type_hint
    hint = get_override(method, 'field') or get_type_hints(method).get('return')
  File "/home/kev/.pyenv/versions/my-project/lib/python3.9/site-packages/drf_spectacular/plumbing.py", line 237, in get_type_hints
    return typing.get_type_hints(obj)
  File "/home/kev/.pyenv/versions/3.9-dev/lib/python3.9/typing.py", line 1497, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "/home/kev/.pyenv/versions/3.9-dev/lib/python3.9/typing.py", line 294, in _eval_type
    ev_args = tuple(_eval_type(a, globalns, localns, recursive_guard) for a in t.__args__)
  File "/home/kev/.pyenv/versions/3.9-dev/lib/python3.9/typing.py", line 294, in <genexpr>
    ev_args = tuple(_eval_type(a, globalns, localns, recursive_guard) for a in t.__args__)
  File "/home/kev/.pyenv/versions/3.9-dev/lib/python3.9/typing.py", line 292, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "/home/kev/.pyenv/versions/3.9-dev/lib/python3.9/typing.py", line 554, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Club' is not defined
```

**Comment by tfranzel** [comment]
From which to which version did you upgrade? There has not been changes in the type system for a while.
Can you narrow down the code location? Example? What is Club? We need more information to address this.

**Comment by huynd26** [comment]
Currently, I'm using  0.23.1 version and tried to upgrade 0.26.2 version. Club just is a model.

**Comment by tfranzel** [comment]
A lot of things changed: https://github.com/tfranzel/drf-spectacular/compare/0.23.1...0.26.2

It seems the error happens in the stdlib with `typing.get_type_hints(obj)`. Maybe we now try to resolve something we did not do before and so this break now. This can have several reasons. We need more context on how you have written that type hint involving `Club`.

**Comment by tfranzel** [comment]
closing this idle issue for now. feel free to comment if anything is missing or not working and we will follow-up.
